export const products = [
  {
    id: 1,
    productName: 'Shoe 1',
    price: '£100',
    description: 'abc',
    category: 'MEN',
    type: 'TRAINERS',
    slug: 'shoe1',
    url: 'https://images.flannels.com/images/products/11690703_4pl.jpg',
  },
  {
    id: 2,
    productName: 'Shoe 2',
    price: '£100',
    description: 'abc',
    category: 'WOMEN',
    type: 'HEELS',
    slug: 'shoe2',
    url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkogC8UkCQ2SSLH1phkbjr6_8opGLUA-HLDQ&usqp=CAU',
  },
  {
    id: 3,
    productName: 'Shoe 3',
    price: '£100',
    description: 'abc',
    category: 'MEN',
    type: 'SANDALS',
    slug: 'shoe3',
    url: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQsxi8Dssisfx0hz0vqhX4L58WP8TZkUhdKd5VVlm6ExuUjt409R53qQhNIX800qTlsdJNozwqFI9XIjs_ts17wZnOlD4Lsnrx8_W8NDdT8VBGoItQhtC74cA&usqp=CAE',
  },
  {
    id: 4,
    productName: 'Shoe 3',
    price: '£100',
    description: 'abc',
    category: 'WOMEN',
    type: 'SANDALS',
    slug: 'shoe4',
    url: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQy1MnrRIzvclueONgTqkHu9pnT-uczM1uTY73zh-VUeTbJ0z1P9esy2BLpQfy9J-e894tq5kz2shKHZslK0vidnPB-ii263ZTIzey-vj4tae1Khmr7cm9E&usqp=CAE',
  },
  {
    id: 5,
    productName: 'Shoe 1',
    price: '£100',
    description: 'abc',
    category: 'MEN',
    type: 'CASUAL',
    slug: 'shoe5',
    url: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRm9O1yUelxQcuD_r2N8PJJ0pe0sUYPzfW-Ih9H-2qsI4gvMqH1IzSLypCZFw6zwhpC4dFOyJqiiKdIYJVKv1bJ4rLkpr_E36ipCEQjg_qmk9NpjP1Byn4t&usqp=CAE',
  },
  {
    id: 6,
    productName: 'Shoe 1',
    price: '£100',
    description: 'abc',
    category: 'MEN',
    type: 'CASUAL',
    slug: 'shoe5',
    url: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQ6g3oajqFoP_2eQhBP01KQ_1cAg68FRmH13k5hK4lEnx7Zlh8DGBqBv1_oqbhkBAKBfHtgR7rUoecqqKavtmZ0UH7inDatzvFY9diqUs5FtEccHC0oTF8h&usqp=CAE',
  },
];
