export const products = [
  {
    id: 1,
    productName: 'Shoe 1',
    price: '£100',
    description: 'abc',
    category: 'MEN',
    type: 'TRAINERS',
    slug: 'shoe1',
    url: 'https://images.flannels.com/images/products/11690703_4pl.jpg',
  },
  {
    id: 2,
    productName: 'Shoe 2',
    price: '£100',
    description: 'abc',
    category: 'WOMEN',
    type: 'HEELS',
    slug: 'shoe2',
    url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkogC8UkCQ2SSLH1phkbjr6_8opGLUA-HLDQ&usqp=CAU',
  },
  {
    id: 3,
    productName: 'Shoe 3',
    price: '£100',
    description: 'abc',
    category: 'MEN',
    type: 'SANDALS',
    slug: 'shoe3',
    url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEeHNSv50aqwHpKyk_RA7RMriZMvq4uNZY8A&usqp=CAU',
  },
  {
    id: 4,
    productName: 'Shoe 3',
    price: '£100',
    description: 'abc',
    category: 'WOMEN',
    type: 'SANDALS',
    slug: 'shoe4',
    url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM2WL2hNnX4Kpk379mI1aE1HLVzg6RJMQJKw&usqp=CAU',
  },
  {
    id: 5,
    productName: 'Shoe 1',
    price: '£100',
    description: 'abc',
    category: 'MEN',
    type: 'CASUAL',
    slug: 'shoe5',
    url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBls0kL98X1zSmj0TgFO4iFN0dmAPlqGCyUg&usqp=CAU',
  },
  {
    id: 6,
    productName: 'Shoe 1',
    price: '£100',
    description: 'abc',
    category: 'MEN',
    type: 'CASUAL',
    slug: 'shoe5',
    url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFKeO2HD6OA5gWueF_1-PaPdUnrkxmBdHRNw&usqp=CAU',
  },
];
